spring.application.name=parcial

#SQL DATABASE CONFIGURATION
gg.jte.development-mode=true

# Configuración de base de datos postgresql
spring.datasource.url=jdbc:postgresql://10.43.103.165:5432/parcial
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user1
spring.datasource.password=1234

# Configuración JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Inicialización SQL
spring.sql.init.mode=always

#Logging
#permite imprimir la query
logging.level.org.hibernate.SQL=DEBUG
#imprime los parametros de las querys
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#Ver errores completos en el servidor
server.error.include-message=always
server.error.include-stacktrace=always